### PR TITLE
Update readme.md and add contributing.md

### PR DESCRIPTION
**Pull request by Jonasvdbo**
Added license information to the readme.md and update the text of purpose of the libary to make it more clear for potential users. 

Also, I added some extra information to the contributing.md

Futhermore, I added SPDX-FileCopyrightText and SPDX-License-Identifier information to the .MD files.

### CODE REVIEW

**Review by Jonasvdbo — COMMENTED** [review]
Signed-off-by: Jonas van den Bogaard <3628277+Jonasvdbo@users.noreply.github.com>

**Comment by dvberkel** [comment]
Hi @Jonasvdbo

Thanks for your contribution. Unfortunately I can't merge your contribution. At the moment there are several merge conflicts and failing checks.

The merge conflicts arise from other contributions that solve problems that your pull request address as well. See for example pull-request #6.

**Comment by dvberkel** [comment]
If you are still willing and able to contribute to the project please open a new pull-request. Specifically focusing on the `CONTRIBUTING.md` file.

**Comment by Jonasvdbo** [comment]
@dvberkel Check. I will create a new pull request and double check which changes are still relevant and which not anymore.

**Pull request closed without merging**
